BCDA-10203: utilize config files instead of hard coded values (#1412)
## 🎫 Ticket

https://jira.cms.gov/browse/BCDA-10203

## 🛠 Changes

- hardcoded values in `parser.go` removed
- renamed some script variables for clearer error messages
- move `loadBCDAParams` function before checking if file is a csv, since
we need access to config files before that call is made

## ℹ️ Context

Changes were made so that config files act as single source of truth,
which reduces configuration drifts, redundant regex, and lowers risk of
bugs/issues.

<!-- If any of the following security implications apply, this PR must
not be merged without Stephen Walter's approval. Explain in this section
and add @SJWalter11 as a reviewer.
  - Adds a new software dependency or dependencies.
  - Modifies or invalidates one or more of our security controls.
  - Stores or transmits data that was not stored or transmitted before.
- Requires additional review of security implications for other reasons.
-->

## 🧪 Validation

tbd integration test

diff --git a/.github/workflows/attribution-import-integration-test.yml b/.github/workflows/attribution-import-integration-test.yml
--- a/.github/workflows/attribution-import-integration-test.yml
+++ b/.github/workflows/attribution-import-integration-test.yml
@@ -63,8 +63,8 @@ jobs:
           cclf8_fname=T.BCD.A0001.ZC8Y${year}.D${date}.T${time}1
           echo "CCLFFILENAME=$cclf8_fname" >> "$GITHUB_ENV"
 
-          csvname=T.PCPB.M${year}11.D${date}.T${time}1
-          echo "CSVFILENAME=$csvname" >> "$GITHUB_ENV"
+          tcocmdcsvname=T.PCPB.M${year}11.D${date}.T${time}1
+          echo "CSVFILENAME=$tcocmdcsvname" >> "$GITHUB_ENV"
 
           guidecsvname=T.GUIDE.GUIDE-00001.Y${year}.D${date}.T${time}1
           echo "GUIDEFILENAME=$guidecsvname" >> "$GITHUB_ENV"
@@ -72,7 +72,7 @@ jobs:
           accesscsvname=T.ACCESS.ACCES00001.Y${year}.D${date}.T${time}1
           echo "ACCESSFILENAME=$accesscsvname" >> "$GITHUB_ENV"
 
-          mv ../shared_files/cclf/archives/csv/P.PCPB.M2411.D181120.T1000000 ${csvname}
+          mv ../shared_files/cclf/archives/csv/P.PCPB.M2411.D181120.T1000000 ${tcocmdcsvname}
 
           mv ../shared_files/cclf/archives/csv/T.GUIDE.GUIDE-00001.Y25.D250630.T1000000 ${guidecsvname}
 
@@ -91,8 +91,8 @@ jobs:
           aws s3 cp --no-progress $fname \
             s3://$BUCKET/bfdeft01/bcda/in/test/$fname
 
-          aws s3 cp --no-progress ${csvname} \
-            s3://$BUCKET/bfdeft01/bcda/in/test/${csvname}
+          aws s3 cp --no-progress ${tcocmdcsvname} \
+            s3://$BUCKET/bfdeft01/bcda/in/test/${tcocmdcsvname}
 
           aws s3 cp --no-progress ${guidecsvname} \
             s3://$BUCKET/bfdeft01/bcda/in/test/${guidecsvname}
@@ -146,23 +146,23 @@ jobs:
             fi
           fi
 
-          # Verify that we have a record of the CSV file in the database
-          CSV_FILE=`psql -t "$CONNECTION_URL" -c "SELECT id FROM cclf_files WHERE name = '$CSVFILENAME' LIMIT 1" 2>&1`
-          echo "CSV_FILE: $CSV_FILE"
-          if [[ $? -ne 0 || -z $CSV_FILE ]]; then
-            echo "CSV: csv_file query returned zero results or command failed"
+          # Verify that we have a record of the TCOCMD CSV file in the database
+          TCOCMD_CSV_FILE=`psql -t "$CONNECTION_URL" -c "SELECT id FROM cclf_files WHERE name = '$CSVFILENAME' LIMIT 1" 2>&1`
+          echo "TCOCMD_CSV_FILE: $TCOCMD_CSV_FILE"
+          if [[ $? -ne 0 || -z $TCOCMD_CSV_FILE ]]; then
+            echo "TCOCMD CSV: csv_file query returned zero results or command failed"
             exit 1
           else
           
             # Verify that the correct number of benes were imported into the database.
-            CSV_BENES=`psql -t "$CONNECTION_URL" -c "SELECT count(mbi) FROM cclf_beneficiaries WHERE file_id = $CSV_FILE" 2>&1`
-            echo "CSV_BENES: $CSV_BENES"
-            if [[ $? -ne 0 || -z $CSV_BENES ]]; then
+            TCOCMD_CSV_BENES=`psql -t "$CONNECTION_URL" -c "SELECT count(mbi) FROM cclf_beneficiaries WHERE file_id = $TCOCMD_CSV_FILE" 2>&1`
+            echo "TCOCMD_CSV_BENES: $TCOCMD_CSV_BENES"
+            if [[ $? -ne 0 || -z $TCOCMD_CSV_BENES ]]; then
               echo "CSV beneficiaries query returned zero results or command failed"
               exit 1
             fi
-            if [[ $(echo $CSV_BENES | xargs) != "5" ]]; then
-              echo "expected 5 beneficiaries imported from file, received $CSV_BENES".
+            if [[ $(echo $TCOCMD_CSV_BENES | xargs) != "5" ]]; then
+              echo "expected 5 beneficiaries imported from file, received $TCOCMD_CSV_BENES".
               exit 1
             fi
           fi
