Test CCLF import

diff --git a/.github/workflows/cclf-import-test-integration.yml b/.github/workflows/cclf-import-test-integration.yml
--- a/.github/workflows/cclf-import-test-integration.yml
+++ b/.github/workflows/cclf-import-test-integration.yml
@@ -29,6 +29,8 @@ jobs:
     defaults:
       run:
         working-directory: bcda
+    outputs:
+      filename: ${{ steps.createfile.outputs.FILENAME }}
     steps:
       - uses: actions/checkout@v4
       - uses: aws-actions/configure-aws-credentials@v4
@@ -43,9 +45,54 @@ jobs:
           role-chaining: true
           role-skip-session-tagging: true
       - name: Upload test file to the BFD bucket to trigger lambda function via SNS message
+        id: createfile
         run: |
-          aws s3 cp --no-progress ../shared_files/cclf/files/synthetic/test/small/ZC0 \
-            s3://bfd-test-eft/bfdeft01/bcda/in/T.NGD.DPC.RSP.D$(date +'%y%m%d').T$(date +'%H%M%S')1.IN
+          fname=T.BCD.A5451.ZCY24.D$(date +'%y%m%d').T$(date +'%H%M%S')1
+          echo "FILENAME=$fname" >> "$GITHUB_OUTPUT"
+          aws s3 cp --no-progress ../shared_files/cclf/archives/valid/T.BCD.ACOB.ZC0Y18.D181120.T0001000 \
+            s3://bfd-test-eft/bfdeft01/bcda/in/test/$fname
 
-  # TODO Check bucket for response file
-  # TODO Run another job to check database for update
+  verify:
+    needs: trigger
+    runs-on: self-hosted
+    env: 
+      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"
+    steps:
+      - uses: actions/checkout@v3
+      - uses: aws-actions/configure-aws-credentials@v3
+        with:
+          aws-region: ${{ vars.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/delegatedadmin/developer/bcda-test-github-actions
+      - name: Install psql
+        run: |
+            sudo amazon-linux-extras install postgresql14
+      - name: Get database credentials
+        uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
+        env:
+          AWS_REGION: ${{ vars.AWS_REGION }}
+        with:
+          params: |
+            CONNECTION_INFO=/bcda/test/api/DATABASE_URL
+      - name: Verify suppression file was ingested
+        env:
+          FILENAME: ${{needs.trigger.outputs.filename}}
+        # CAUTION: if changing the script below, validate that sensitive information is not printed in the workflow
+        run: |
+          HOST=$(aws rds describe-db-instances --db-instance-identifier bcda-test-rds 2>&1 | jq -r '.DBInstances[0].Endpoint.Address' 2>&1)
+          CONNECTION_URL=$(echo $CONNECTION_INFO 2>&1 | sed -E "s/@.*\/bcda/\@$HOST\/bcda/" 2>&1)
+          CCLF_FILE=`psql -t "$CONNECTION_URL" -c "SELECT id FROM cclf_files WHERE name = '$FILENAME' LIMIT 1" 2>&1`
+          if [[ $? -ne 0 || -z $CCLF_FILE ]]; then
+            echo "cclf_file query returned zero results or command failed"
+            exit 1
+          else
+            CCLF_BENES=`psql -t "$CONNECTION_URL" -c "SELECT count(mbi) FROM cclf_beneficiaries WHERE file_id = $CCLF_FILE" 2>&1`
+              if [[ $? -ne 0 || -z $CCLF_BENES ]]; then
+                echo "suppressions query returned zero results or command failed"
+                exit 1
+              fi
+              if [[ "$CCLF_BENES" != "6" ]]; then
+                echo "expected 6 beneficiaries imported from file, received $CCLF_BENES".
+                exit 1
+              fi
+          fi
+            
