BCDA-10135: add access model attribution (#1403)
## 🎫 Ticket

https://jira.cms.gov/browse/BCDA-10135

## 🛠 Changes

- added ACCESS model csv attribution ingestion (entity id placeholder
present; still awaiting)
- updated api.yml with ACCESS model
- minor comment cleanup
- moved IsSupportedACO() from service to config; config package had
other `IsXYXACO` methods and this had hardcoded regex expressions that
had drift from our aco configuration files.
- removed some unused methods to convert struct to string and some used
methods for the aforementioned
- add test attribution file for ACCESS model.

## ℹ️ Context

*Holding off on merging this PR until we get the entity ID naming
convention for ACCESS.*

PR is part of effort to add ACCESS model attribution. Did some minor
cleanup for verifying if an ACO ID is valid; we have regex in our config
files and we had a function with hardcoded values; there was drift
between the two, so the hardcoded func was updated to instead check
against the aco configs, since that is our source of truth.

<!-- If any of the following security implications apply, this PR must
not be merged without Stephen Walter's approval. Explain in this section
and add @SJWalter11 as a reviewer.
  - Adds a new software dependency or dependencies.
  - Modifies or invalidates one or more of our security controls.
  - Stores or transmits data that was not stored or transmitted before.
- Requires additional review of security implications for other reasons.
-->

## 🧪 Validation

Unit tests passing. Integration tests passing.

---------

Co-authored-by: Parwinder Bhagat <Parwinder.Bhagat@e14s.com>

diff --git a/.github/workflows/cclf-import-integration-test.yml b/.github/workflows/cclf-import-integration-test.yml
--- a/.github/workflows/cclf-import-integration-test.yml
+++ b/.github/workflows/cclf-import-integration-test.yml
@@ -71,10 +71,15 @@ jobs:
           guidecsvname=T.GUIDE.GUIDE-00001.Y${year}.D${date}.T${time}1
           echo "GUIDEFILENAME=$guidecsvname" >> "$GITHUB_ENV"
 
+          accesscsvname=T.ACCESS.ACCES00001.Y${year}.D${date}.T${time}1
+          echo "ACCESSFILENAME=$accesscsvname" >> "$GITHUB_ENV"
+
           mv ../shared_files/cclf/archives/csv/P.PCPB.M2411.D181120.T1000000 ${csvname}
 
           mv ../shared_files/cclf/archives/csv/T.GUIDE.GUIDE-00001.Y25.D250630.T1000000 ${guidecsvname}
 
+          mv ../shared_files/cclf/archives/csv/T.ACCESS.ACCES00001.Y25.D250630.T1000000 ${accesscsvname}
+          
           unzip ../shared_files/cclf/archives/valid/T.BCD.A0001.ZCY18.D181120.T1000000
 
           # Clone the synthetic zip file with updated years
@@ -93,6 +98,9 @@ jobs:
 
           aws s3 cp --no-progress ${guidecsvname} \
             s3://bfd-test-eft/bfdeft01/bcda/in/test/${guidecsvname}
+
+          aws s3 cp --no-progress ${accesscsvname} \
+            s3://bfd-test-eft/bfdeft01/bcda/in/test/${accesscsvname}
       # Give a bit of time for lambdas to process files
       - run: sleep 60
       - uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
@@ -162,6 +170,27 @@ jobs:
 
           # Verify that we have a record of the GUIDE CSV file in the database
           CSV_FILE=`psql -t "$CONNECTION_URL" -c "SELECT id FROM cclf_files WHERE name = '$GUIDEFILENAME' LIMIT 1" 2>&1`
+          echo "CSV_FILE: $CSV_FILE"
+          if [[ $? -ne 0 || -z $CSV_FILE ]]; then
+            echo "csv_file query returned zero results or command failed"
+            exit 1
+          else
+            
+            # Verify that the correct number of benes were imported into the database.
+            CSV_BENES=`psql -t "$CONNECTION_URL" -c "SELECT count(mbi) FROM cclf_beneficiaries WHERE file_id = $CSV_FILE" 2>&1`
+            echo "CSV_BENES: $CSV_BENES"
+            if [[ $? -ne 0 || -z $CSV_BENES ]]; then
+              echo "CSV beneficiaries query returned zero results or command failed"
+              exit 1
+            fi
+            if [[ $(echo $CSV_BENES | xargs) != "5" ]]; then
+              echo "expected 5 beneficiaries imported from file, received $CSV_BENES".
+              exit 1
+            fi
+          fi
+
+          # Verify that we have a record of the ACCESS CSV file in the database
+          CSV_FILE=`psql -t "$CONNECTION_URL" -c "SELECT id FROM cclf_files WHERE name = '$ACCESSFILENAME' LIMIT 1" 2>&1`
           echo "CSV_FILE: $CSV_FILE"
           if [[ $? -ne 0 || -z $CSV_FILE ]]; then
             echo "csv_file query returned zero results or command failed"
