Quick fixes, add loggers to cclf import test

diff --git a/.github/workflows/cclf-import-integration-test-GF.yml b/.github/workflows/cclf-import-integration-test-GF.yml
--- a/.github/workflows/cclf-import-integration-test-GF.yml
+++ b/.github/workflows/cclf-import-integration-test-GF.yml
@@ -114,16 +114,19 @@ jobs:
             CONNECTION_INFO=/bcda/test/api/DATABASE_URL
       - name: Verify CCLF file was ingested
         env:
-          CCLFFILENAME: ${{needs.trigger.outputs.cclffilename}}
-          CSVFILENAME: ${{needs.trigger.outputs.csvfilename}}
+          CCLFFILENAME: ${{ needs.trigger.outputs.cclffilename }}
+          CSVFILENAME: ${{ needs.trigger.outputs.csvfilename }}
           PGSSLMODE: require
         # CAUTION: if changing the script below, validate that sensitive information is not printed in the workflow
         run: |
           HOST=$(aws rds describe-db-instances --db-instance-identifier bcda-test 2>&1 | jq -r '.DBInstances[0].Endpoint.Address' 2>&1)
+          echo $HOST | cut -c -10
           CONNECTION_URL=$(echo $CONNECTION_INFO 2>&1 | sed -E "s/@.*\/bcda/\@$HOST\/bcda/" 2>&1)
+          echo $CONNECTION_URL | cut -c 5
 
           # Verify that we have a record of the CCLF file in the database
           CCLF_FILE=`psql -t "$CONNECTION_URL" -c "SELECT id FROM cclf_files WHERE name = '$CCLFFILENAME' LIMIT 1" 2>&1`
+          echo "CCLF_FILE: $CCLF_FILE"
           if [[ $? -ne 0 || -z $CCLF_FILE ]]; then
             echo "cclf_file query returned zero results or command failed"
             exit 1
@@ -131,18 +134,20 @@ jobs:
             
             # Verify that the correct number of benes were imported into the database.
             CCLF_BENES=`psql -t "$CONNECTION_URL" -c "SELECT count(mbi) FROM cclf_beneficiaries WHERE file_id = $CCLF_FILE" 2>&1`
-              if [[ $? -ne 0 || -z $CCLF_BENES ]]; then
-                echo "CCLF beneficiaries query returned zero results or command failed"
-                exit 1
-              fi
-              if [[ $(echo $CCLF_BENES | xargs) != "6" ]]; then
-                echo "expected 6 beneficiaries imported from file, received $CCLF_BENES".
-                exit 1
-              fi
+            echo "CCLF_BENES: $CCLF_BENES"
+            if [[ $? -ne 0 || -z $CCLF_BENES ]]; then
+              echo "CCLF beneficiaries query returned zero results or command failed"
+              exit 1
+            fi
+            if [[ $(echo $CCLF_BENES | xargs) != "6" ]]; then
+              echo "expected 6 beneficiaries imported from file, received $CCLF_BENES".
+              exit 1
+            fi
           fi
 
           # Verify that we have a record of the CSV file in the database
           CSV_FILE=`psql -t "$CONNECTION_URL" -c "SELECT id FROM cclf_files WHERE name = '$CSVFILENAME' LIMIT 1" 2>&1`
+          echo "CSV_FILE: $CSV_FILE"
           if [[ $? -ne 0 || -z $CSV_FILE ]]; then
             echo "csv_file query returned zero results or command failed"
             exit 1
@@ -150,14 +155,15 @@ jobs:
             
             # Verify that the correct number of benes were imported into the database.
             CSV_BENES=`psql -t "$CONNECTION_URL" -c "SELECT count(mbi) FROM cclf_beneficiaries WHERE file_id = $CSV_FILE" 2>&1`
-              if [[ $? -ne 0 || -z $CSV_BENES ]]; then
-                echo "CSV beneficiaries query returned zero results or command failed"
-                exit 1
-              fi
-              if [[ $(echo $CSV_BENES | xargs) != "5" ]]; then
-                echo "expected 5 beneficiaries imported from file, received $CSV_BENES".
-                exit 1
-              fi
+            echo "CSV_BENES: $CSV_BENES"
+            if [[ $? -ne 0 || -z $CSV_BENES ]]; then
+              echo "CSV beneficiaries query returned zero results or command failed"
+              exit 1
+            fi
+            if [[ $(echo $CSV_BENES | xargs) != "5" ]]; then
+              echo "expected 5 beneficiaries imported from file, received $CSV_BENES".
+              exit 1
+            fi
           fi
 
 
