happy path to unhappy path

diff --git a/.github/workflows/opt-out-import-test-integration.yml b/.github/workflows/opt-out-import-test-integration.yml
--- a/.github/workflows/opt-out-import-test-integration.yml
+++ b/.github/workflows/opt-out-import-test-integration.yml
@@ -73,7 +73,15 @@ jobs:
           CONNECTION_URL="postgresql://user:password@rds.bcda-test.local/bcda"
           HOST="foo-bar"
           CONN_REP=$(echo $CONNECTION_URL | sed -E "s/@.*\/bcda/\@$HOST\/bcda\//")
-          SUPPRESSION_FILE=$("foo bar")
+          SUPPRESSION_FILE=$(echo "foo bar")
           
-
+          if [[ $? -ne 0 || -z $SUPPRESSION_FILE ]]; then
+            echo "Query returned zero results or command failed"
+            exit 1
+          else
+            SUPPRESSIONS=`psql -t "$CONN_REP" -c "SELECT * FROM suppression_files WHERE file_id = $SUPPRESSION_FILE" 2>&1`
+              if [[ $? -ne 0 || -z $SUPPRESSIONS ]]; then
+                echo "Query returned zero results or command failed"
+                exit 1
+          fi
             
