testing full script

diff --git a/.github/workflows/opt-out-import-test-integration.yml b/.github/workflows/opt-out-import-test-integration.yml
--- a/.github/workflows/opt-out-import-test-integration.yml
+++ b/.github/workflows/opt-out-import-test-integration.yml
@@ -55,13 +55,13 @@ jobs:
     needs: trigger
     runs-on: self-hosted
     steps:
-      # - name: Get database credentials
-      #   uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
-      #   env:
-      #     AWS_REGION: ${{ vars.AWS_REGION }}
-      #   with:
-      #     params: |
-      #       CONNECTION_URL=/bcda/test/api/DATABASE_URL
+      - name: Get database credentials
+        uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
+        env:
+          AWS_REGION: ${{ vars.AWS_REGION }}
+        with:
+          params: |
+            CONNECTION_INFO=/bcda/test/api/DATABASE_URL
       - name: Install psql
         run: |
             sudo amazon-linux-extras install postgresql14
@@ -70,15 +70,17 @@ jobs:
           FILENAME: ${{needs.trigger.outputs.filename}}
         # CAUTION: if changing the script below, validate that sensitive information is not printed in the workflow
         run: |
-          CONNECTION_URL="postgresql://user:password@rds.bcda-test.local/bcda"
-          HOST="foo-bar"
-          CONN_REP=$(echo $CONNECTION_URL | sed -E "s/@.*\/bcda/\@$HOST\/bcda\//")
-          SUPPRESSION_FILE=$(echo "foo bar")
-          
+          HOST=$(aws rds describe-db-instances --db-instance-identifier bcda-test-rds | jq -r '.DBInstances[0].Endpoint.Address')
+          CONNECTION_URL=$(echo $CONNECTION_INFO | sed -E "s/@.*\/bcda/\@$HOST\/bcda/")
+          SUPPRESSION_FILE=`psql -t "$CONNECTION_URL" -c "SELECT id FROM suppression_files WHERE name = '$FILENAME' LIMIT 1" 2>&1`
           if [[ $? -ne 0 || -z $SUPPRESSION_FILE ]]; then
-            echo "Query returned zero results or command failed"
+            echo "suppression_file query returned zero results or command failed"
             exit 1
           else
-            echo "success"
+            SUPPRESSIONS=`psql -t "$CONNECTION_URL" -c "SELECT count(mbi) FROM suppressions WHERE file_id = $SUPPRESSION_FILE" 2>&1`
+              if [[ $? -ne 0 || -z $SUPPRESSIONS ]]; then
+                echo "suppressions query returned zero results or command failed"
+                exit 1
+              fi
           fi
             
