update connection string

diff --git a/.github/workflows/refresh_test_attribution.yml b/.github/workflows/refresh_test_attribution.yml
--- a/.github/workflows/refresh_test_attribution.yml
+++ b/.github/workflows/refresh_test_attribution.yml
@@ -40,13 +40,41 @@ jobs:
       - name: Refresh all environments
         run: |
           set -euo pipefail
-          ENVS=($DEV_DB, $TEST_DB, $SBX_DB, $PROD_DB)
-          for conn in ${ENVS[@]}; do
-            ./scripts/refresh_test_attribution.sh -c "${conn}" -f > /dev/null 2>&1
+
+          declare -A environments
+
+          environments["dev"]=$DEV_DB
+          environments["test"]=$TEST_DB
+          # environments["opensbx"]=$TEST_DB
+          # environments["prod"]=$PROD_DB
+
+          for key in "${!environments[@]}"; do
+
+            value="${environments[$key]}"
+            echo "Key: $key, Value: $value"
+
+            HOST=$(aws rds describe-db-instances --db-instance-identifier bcda-$key-rds 2>&1 | jq -r '.DBInstances[0].Endpoint.Address' 2>&1)
+            CONNECTION_URL=$(echo $value 2>&1 | sed -E "s/@.*\/bcda/\@$HOST\/bcda/" 2>&1)
+
+            ./scripts/refresh_test_attribution.sh -c "${CONNECTION_URL}" -f > /dev/null 2>&1
+            
             if [ $? -ne 0 ]; then
               echo "Refresh failed. Run script locally for more details."
             else 
               echo "Refresh Successful."
             fi
           done
+
+
+
+
+          # ENVS=($DEV_DB, $TEST_DB, $TEST_DB, $PROD_DB)
+          # for conn in ${ENVS[@]}; do
+          #   ./scripts/refresh_test_attribution.sh -c "${conn}" -f > /dev/null 2>&1
+          #   if [ $? -ne 0 ]; then
+          #     echo "Refresh failed. Run script locally for more details."
+          #   else 
+          #     echo "Refresh Successful."
+          #   fi
+          # done
           
